name: SwgClient Build and Deploy

on: [push, pull_request, workflow_dispatch]

env:
  SOLUTION_FILE_PATH: src/game/client/application/SwgClient/build/win32/SwgClient.vcxproj

jobs:
  build:
    runs-on: windows-2016

    steps:
    - run: Configure Build
        echo "Acquire VS 2013"
        curl http://download.microsoft.com/download/7/1/B/71BA74D8-B9A0-4E6C-9159-A8335D54437E/vs_community.exe -o vs_community.exe
        echo "Install VS 2013"
        .\vs_community.exe /norestart /passive
        echo "Install MS Build Tools v120"
        choco install microsoft-build-tools-2013 -y
        echo "SDK Version..."
        echo $(Get-Item "hklm:\SOFTWARE\Microsoft\Microsoft SDKs\Windows").GetValue("CurrentVersion")
        echo "Validate VS Install..."
        Get-ChildItem "C:\Program Files (x86)\Microsoft Visual Studio 12.0"
        
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Release Client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        mkdir C:\vs13deps
        git clone -v https://github.com/aconitex/vs13deps.git "C:\vs13deps"
        $env:VCTargetsPath = "C:\vs13deps\Microsoft.Cpp\v4.0\V120"
        & "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" -ds -v:diag -p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}
        
