name: SwgClient (Release)

on: [push, pull_request, workflow_dispatch]

env:
  SOLUTION_FILE_PATH: src/game/client/application/SwgClient/build/win32/SwgClient.vcxproj

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Acquire Dependencies and Configure
      run: |
        choco install vcredist2013 -y
        choco install microsoft-build-tools-2013 -y
        choco install visualstudiocommunity2013 -y
        
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        $env:VCTargetsPath = "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\"
        & "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" -ds -v:diag -p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}
        
