name: SwgClient Build and Deploy

on: [push, pull_request, workflow_dispatch]

env:
  SOLUTION_FILE_PATH: src/game/client/application/SwgClient/build/win32/SwgClient.vcxproj

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Acquire Dependencies
      run: |
        choco install vcredist2013 -y
        choco install microsoft-build-tools-2013 -y
      
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build Release Client
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        git clone -v https://github.com/aconitex/vs13deps.git
        $env:VCTargetsPath = "vs13deps\Microsoft.Cpp\v4.0\V120"
        & "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" -ds -v:diag -p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}     
